export type ZeevRequestCatalogItem = {
  id: string;
  name: string;
  area: 'TI';
  description: string;
  tags: string[];
  examples: string[];
  url_hml: string;
  url_prod?: string;
};

export const REQUESTS_CATALOG: ZeevRequestCatalogItem[] = [
  {
    id: 'ti_infraestrutura',
    name: 'TI — Solicitações de Infraestrutura',
    area: 'TI',
    description:
      'Solicitações relacionadas à infraestrutura de TI, como redes, computadores, equipamentos, VPN e acessos técnicos.',
    tags: [
      'ti',
      'infraestrutura',
      'infra',
      'rede',
      'internet',
      'vpn',
      'computador',
      'pc',
      'notebook',
      'equipamento',
      'hardware',
      'impressora',
      'acesso',
      'servidor',
      'erro tecnico',
      'lento',
      'travou',
      'nao liga',
      'wifi',
      'formatar',
      'periferico',
      'mouse',
      'teclado',
      'monitor',
      'camera',
      'microfone',
      'windows',
      'tela azul',
      'reinicia',
      'maquina',
    ],
    examples: [
      'meu computador não funciona',
      'meu computador não liga',
      'o PC está lento',
      'o notebook travou',
      'preciso formatar o computador',
      'preciso de um computador novo',
      'meu computador está muito lento',
      'a máquina travou',
      'o Windows não inicia',
      'deu tela azul',
      'o computador reinicia sozinho',
      'a internet não funciona',
      'estou sem internet',
      'a rede caiu',
      'wifi não conecta',
      'não consigo acessar a rede',
      'a impressora não funciona',
      'não consigo imprimir',
      'o mouse não funciona',
      'o teclado não funciona',
      'monitor não liga',
      'a câmera não funciona',
      'o microfone não funciona',
      'preciso instalar um programa',
      'preciso configurar o computador',
    ],
    url_hml:
      'https://hmlraizeducacao.zeev.it/2.0/request?c=m71LtsDaPTCgWOFkxULi2ovOU2%2F%2FTJXgYfYS73zejPX2sLmPGMjjDmN9LYksPeLKsV4hVWif%2B0sD%2Fh6aQkeQAg%3D%3D',
    url_prod:
      'https://raizeducacao.zeev.it/2.0/request?c=tecnologia-da-informacao-ti&pid=infraestrutura',
  },
  {
    id: 'ti_ticket_raiz',
    name: 'TI — Solicitações Ticket Raiz',
    area: 'TI',
    description:
      'Solicitações gerais de TI como criação/cancelamento de tickets, criação de usuário, desbloqueios e demandas administrativas de TI.',
    tags: [
      'ti',
      'ticket',
      'chamado',
      'abrir chamado',
      'cancelar chamado',
      'cancelamento',
      'usuario',
      'criar usuario',
      'bloqueio',
      'desbloqueio',
      'perfil',
      'acesso sistema',
      'solicitacao',
      'acesso',
      'senha',
      'login',
      'duvida',
      'atendimento',
      'pedido',
      'ajuda',
      'liberar acesso',
      'trocar perfil',
      'alterar permissao',
      'resetar senha',
      'login bloqueado',
      'nao consigo logar',
      'acesso bloqueado',
      'fechar chamado',
    ],
    examples: [
      'quero abrir um chamado',
      'preciso abrir um ticket',
      'abrir solicitação',
      'abrir pedido',
      'abrir atendimento',
      'preciso de ajuda',
      'tenho uma dúvida',
      'não sei onde solicitar isso',
      'quero cancelar um chamado',
      'cancelar ticket',
      'fechar chamado',
      'criar usuário',
      'preciso criar um usuário',
      'liberar acesso',
      'me dar acesso',
      'não tenho acesso',
      'trocar perfil',
      'alterar permissão',
      'esqueci minha senha',
      'trocar senha',
      'resetar senha',
      'login bloqueado',
      'não consigo logar',
      'acesso bloqueado',
    ],
    url_hml:
      'https://hmlraizeducacao.zeev.it/2.0/request?c=k%2BoKhoSJ9Gz33Fq%2Fe2M0%2B9v93wMmOwIzRKyj9me2KkX1v%2Bv2Sv2PrK3iQVVLQ6hOrOBurixLij%2FIf2P21uRNfg%3D%3D',
    url_prod:
      'https://raizeducacao.zeev.it/2.0/request?c=tecnologia-da-informacao-ti&pid=ticket-raiz',
  },
  {
    id: 'ti_sistemas',
    name: 'TI — Solicitações de Sistemas',
    area: 'TI',
    description:
      'Solicitações relacionadas a sistemas internos, erros, falhas, ajustes e suporte a aplicações.',
    tags: [
      'ti',
      'sistemas',
      'sistema',
      'erro no sistema',
      'bug',
      'falha',
      'nao funciona',
      'acesso sistema',
      'aplicacao',
      'software',
      'rm',
      'totvs',
      'travou',
      'nao abre',
      'processo',
      'fluxo',
      'instabilidade',
      'integracao',
      'melhoria',
      'caiu',
      'carregando',
      'mensagem de erro',
      'erro ao salvar',
      'nao consigo lancar',
      'nao consigo aprovar',
      'botao nao funciona',
      'funcionalidade',
      'fora do ar',
    ],
    examples: [
      'o sistema está com erro',
      'o sistema não funciona',
      'o sistema caiu',
      'o sistema travou',
      'não consigo acessar o sistema',
      'não entra no sistema',
      'o sistema não abre',
      'fica carregando',
      'aparece uma mensagem de erro',
      'erro no sistema',
      'erro ao salvar',
      'não consigo lançar',
      'não consigo aprovar',
      'a tela travou',
      'o botão não funciona',
      'a funcionalidade não aparece',
      'processo travado',
      'fluxo parado',
      'problema no Totvs',
      'erro no RM',
      'sistema fora do ar',
      'instabilidade no sistema',
      'preciso de melhoria no sistema',
      'preciso integrar sistemas',
    ],
    url_hml:
      'https://hmlraizeducacao.zeev.it/2.0/request?c=YhDfnY6X6UBJ7lxD4KxaekF%2F23pF24mDPHnDvzngYhHt2QIJw24dD5D1yEI%2F8Ya5IjZfO0DehsariU16cMhpDg%3D%3D',
    url_prod:
      'https://raizeducacao.zeev.it/2.0/request?c=tecnologia-da-informacao-ti&pid=sistemas',
  },
  {
    id: 'ti_bi',
    name: 'TI — Solicitações de Business Intelligence (BI)',
    area: 'TI',
    description:
      'Solicitações relacionadas a dados, relatórios, dashboards, análises e BI.',
    tags: [
      'ti',
      'bi',
      'business intelligence',
      'relatorio',
      'dashboard',
      'dados',
      'analise',
      'indicador',
      'kpi',
      'painel',
      'power bi',
      'grafico',
      'extracao',
      'excel',
      'planilha',
      'base',
      'comparativo',
      'levantamento',
      'numeros',
      'informacoes',
      'gerencial',
    ],
    examples: [
      'preciso de um relatório',
      'quero um relatório gerencial',
      'preciso de números',
      'preciso de dados',
      'quero extrair dados',
      'quero os dados em Excel',
      'preciso de uma planilha',
      'quero analisar esses dados',
      'preciso dessas informações',
      'tem como puxar esses dados?',
      'preciso de um levantamento',
      'preciso de um comparativo',
      'quero ver indicadores',
      'preciso de um dashboard',
      'quero um painel de controle',
      'preciso acompanhar esses números',
      'preciso de apoio para tomada de decisão',
      'não consigo montar esse relatório',
      'preciso cruzar informações',
      'dados atualizados',
    ],
    url_hml:
      'https://hmlraizeducacao.zeev.it/2.0/request?c=3lr7SkKj4Com%2F912Il9pgXt5NCDNc2RtfehhjVWSqXFUKqCc%2BBJTZTYK0vZl%2BWHc2NZ%2ByeVga7oTHFNmNrnIdA%3D%3D',
    url_prod:
      'https://raizeducacao.zeev.it/2.0/request?c=tecnologia-da-informacao-ti&pid=business-intelligence',
  },
];
